# Generated by Django 5.1.2 on 2024-10-24 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librarian',
            options={'permissions': [('view_book', 'Can view book'), ('add_book', 'Can add book'), ('change_book', 'Can change book'), ('delete_book', 'Can delete book'), ('add_libraryrecord', 'Can add library record'), ('view_libraryrecord', 'Can view library record'), ('change_libraryrecord', 'Can change library record'), ('delete_libraryrecord', 'Can delete library record')], 'verbose_name': 'Librarian', 'verbose_name_plural': 'Librarians'},
        ),
    ]
